[package]
name = "sqk"
version = "0.1.0"
publish = false
edition = "2024"
rust-version = "1.87.0"
license = "MIT"
repository = "https://github.com/chfuchte/sqk"
homepage = "https://github.com/chfuchte/sqk"

[[bin]]
name = "sqk"
path = "src/main.rs"

[dependencies]
