[toolchain]
channel = "1.87.0"
profile = "minimal"
components = ["rustfmt", "clippy"]
targets = [
    "aarch64-apple-darwin",    # macOS ARM64/ Apple Silicon
    "x86_64-apple-darwin",     # macOS
    "aarch64-pc-windows-msvc", # windows Arm64
    "x86_64-pc-windows-msvc",   # windows x86_64#
    "x86_64-unknown-linux-gnu", # linux
]
