name: CI Tests

on:
    pull_request:
        types: [labeled]
        branches: ["master"]

jobs:
    tests:
        if: contains(github.event.pull_request.labels.*.name, 'testing')
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Tests
              run: cargo test
